vocdoni/votecaster

farcasterapi/neynar/neynar.go
farcasterapi/neynar/types.go

new method to get users of a channel, some neynar structs have been updated

Feature: New method to get user data of a Warpcast Channel using Neynar API

---

election.go
shortener/shortener.go
votebot.go

Integrating [`frame.vote`](https://frame.vote/) shortener links service in vote-frame.

Feature: shorted election links

---

bot/handler.go
census.go
election.go
farcasterapi/api.go
farcasterapi/hub/hub.go
farcasterapi/hub/types.go
farcasterapi/neynar/neynar.go
farcasterapi/neynar/types.go
frametemplates.go
handler.go
imageframe/imageframe.go
main.go

New API endpoint `POST /census/followers/{userFid}` to request a new census based on the followers of the user provided. This new endpoint follows the same flow of the csv or channel gated endpoints.
This is a initial and "dummy" implementation, i will work in some improvements, but it works :)

Feature: create census based on user followers census

---

census.go
farcasterapi/api.go
farcasterapi/hub/hub.go
farcasterapi/hub/types.go
farcasterapi/neynar/neynar.go
farcasterapi/neynar/types.go

* Concurrent queries to database for censuses based on followers and channels.
* Channels now can track the progress from the begining.
* Progress of methods are now tracked using channels between methods. 
* Single `vocdoniHandler` method to update and track the progress of an action, even if the whole process has more than a single step: `trackStepProgress(censusID types.HexBytes, step, totalSteps int, action func(chan int))`
* Integrated this flow for CSV censuses too.

Feature: optimized channel and followers census 

---

census.go
webapp/src/components/Form.tsx

including author profile in both sides, add it to the census

feature: including author in followers censuses

---

webapp/package.json
webapp/pnpm-lock.yaml
webapp/src/assets/airstack.svg
webapp/src/components/Form.tsx
webapp/src/vite-env.d.ts
webapp/vite.config.ts

- Added selector for NFT and ERC20 census type via airstack
- Blockchains are currently hardcoded
- Couldn't try anything, since the API is not yet published
- Should work as far as it follows the other census types

PoC of airstack censuses

---

main.go
mongo/notifications.go
mongo/types.go
notifications/notifications.go

basic implementation, notification manager configuration introduced, some logic introduced to request permission to notify to a user before send notifications, database notifications documents updated to include a notification deadline time

feature: handle notification permission management using the bot and a frame

---

election.go
mongo/notifications.go
notifications/notifications.go

* notification deadline calculated based on election ends date:
* deadline = 10 minutes before the election ends if the election ends in less than 3 hours 
* otherwise, deadline = 3 hours before the election ends.
* fixing notification deadline overwrite

bug: missing queued notifications

---

webapp/src/components/Form.tsx

@lucasmenendez I assigned it to you, since AFAIK you haven't published the backend changes yet.

Add custom notification text input field

---

bot/bot.go
election.go
farcasterapi/api.go
farcasterapi/hub/helpers.go
farcasterapi/hub/hub.go
farcasterapi/hub/types.go
farcasterapi/neynar/neynar.go
main.go
mongo/notifications.go
mongo/types.go
notifications/notifications.go
types.go
votebot.go
webapp/src/components/Form.tsx

New texts and support for custom text.

F: new notifications

---

airstack/airstack.go
airstack/client/token.go
census.go

use airstack for getting token decimals

---

main.go
users.go

include new endpoints to mute and unmute users using their usernames

feature: manage notifications mutes via api

---

census.go
channels.go
communities.go
farcasterapi/api.go
farcasterapi/hub/hub.go
farcasterapi/neynar/neynar.go
farcasterapi/neynar/types.go
main.go
mongo/community.go
mongo/mongo.go
mongo/types.go
types.go

feature: new endpoints for communities

---

webapp/src/router/index.tsx
webapp/vite.config.ts

Refactor vite config to use .env file

Implement vite .env file

---

webapp/src/util/constants.ts
webapp/vite.config.ts

Use
DEGEN_CONTRACT_ADDRESS -> VOCDONI_COMMUNITYHUBADDRESS 
RESULTS_CONTRACT_ADDRESS -> VOCDONI_COMMUNITYRESULTSADDRESS

Refactor env vars names

---

census.go
results.go

Some questions I have:
- Is it fine to set the date equal to the date where the election finished ?
- Do we really want to store the turnout as it is? I need to truncate it cause solidity does not support floats
- How I can get the total voting power from the election || electiondb struct ?
- Do we really want to store the list of participants? How I can get it from the election || electiondb struct ?

add results to community hub contract

---

webapp/src/components/Communities/Create/Confirm.tsx

Fix community estimation

---

webapp/src/components/Communities/View.tsx

It shows a horizontal scroll only on the table div which is more friendly for the user on little screens

Fix table overflow

---

census.go
election.go
handler.go
mongo/census.go
mongo/types.go
results.go
types.go

Reorg code and some minor fixes
Correctly return the total users when creating censuses Add census URL to the database

refactor some results parts

---

webapp/src/components/Layout/index.tsx

new footer design with social links

---

communities.go
communityhub/helpers.go
communityhub/hub.go
main.go
mongo/community.go
mongo/types.go
types.go
webapp/src/components/Communities/Card.tsx
webapp/src/components/Communities/View.tsx
webapp/src/components/Communities/index.tsx
webapp/src/queries/communities.ts
webapp/src/util/types.ts

- Listen for contract events about enable or disable communities to update the database.
- Handle user requests updating disable community endpoint to support also to enable a community.
- Basic UI changes.

feature: handle disable enable community events

---

webapp/src/components/Census/ParticipantsTable.tsx
webapp/src/components/CensusTypeSelector.tsx
webapp/src/components/Poll.tsx
webapp/src/components/Poll/CensusListModal.tsx
webapp/src/components/Poll/DownloadButtons.tsx
webapp/src/components/Poll/Information.tsx
webapp/src/components/Poll/Turnout.tsx
webapp/src/generator.ts
webapp/src/pages/Poll.tsx
webapp/src/pages/communities/poll.tsx
webapp/src/queries/census.ts
webapp/src/queries/polls.ts
webapp/src/util/files.ts
webapp/types.d.ts

Working on the census list rn, that's why is set as draft

Download voters list + show census list

---

election.go
frametemplates.go
imageframe/imageframe.go

**Cannot be merged** until https://github.com/vocdoni/ts-vote-frame/pull/2 is merged and deployed

Update images ratio + point to ms for missing images

---

webapp/src/pages/Profile.tsx
webapp/src/queries/profile.ts
webapp/types.d.ts

See issue https://github.com/vocdoni/vote-frame/issues/125
The screenshot shows the expected result on the profile page

Show degen or ens name if any on the profile page

---

airstack/client/farcaster.go
airstack/client/token.go
airstack/graphql/generated.go
airstack/graphql/genqlient.yaml
airstack/graphql/queries/farcaster.graphql
airstack/graphql/queries/token.graphql
airstack/graphql/schema.graphql

- Get farcaster follower count given a fid
- Check if a given user follows a another given user (using FIDs)
- Check if an EVM address holds a given token in a given chain
This commit should allow to check all agreed queries for computing reputation.

Add support for more Airstack queries:

---

README.md
frametemplates.go
webapp/src/components/Auth/Reputation.tsx
webapp/src/components/Communities/Form/index.tsx
webapp/src/components/Credits.tsx
webapp/src/components/Home/Features.tsx
webapp/src/components/Home/Tired.tsx
webapp/src/components/Layout/Navbar.tsx

Votecaster renaming

---

main.go

Handle robots.txt (the same way we handle favicon.ico

---

mongo/election.go
mongo/votes.go
webapp/src/components/Poll/PollRemindersModal.tsx
webapp/src/components/Poll/RemainingVotersTableModal.tsx

Includes:
- Single context to get census info and update the voters list.
- Use `Lock/Unlock` and `RLock/RUnlock` to avoid races.

reminders for large censuses
